FROM python:3.13

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

COPY pyproject.toml ./
RUN uv sync

COPY ingest_data.py load_data.py ./
COPY green_tripdata_2025-11.parquet taxi_zone_lookup.csv ./

ENTRYPOINT ["uv", "run", "python", "load_data.py"]
